name: Get latest package stats from pypi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get latest PyPI stats
      run: |
        curl "https://pypistats.org/api/packages/yahoo-finance-api/overall?mirrors=true" >> stats.json
    - name: Commit and push if s changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push